//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSAF_Forms
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSAF_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RSAF_MASTER()
        {
            this.RSAF_DETAIL = new HashSet<RSAF_DETAIL>();
            this.RSAF_MASTER_HIST = new HashSet<RSAF_MASTER_HIST>();
        }
    
        public System.DateTime CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public bool STATUS { get; set; }
        public long MASTER_ID { get; set; }
        public string BAEPO { get; set; }
        public string BAEPART { get; set; }
        public string SITE { get; set; }
        public string TYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public string ROID_NO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSAF_DETAIL> RSAF_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSAF_MASTER_HIST> RSAF_MASTER_HIST { get; set; }
        public virtual RSAF_SITE RSAF_SITE { get; set; }
        public virtual RSAF_TYPE RSAF_TYPE { get; set; }
    }
}
