//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSAF_Forms
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RsafDbContext : DbContext
    {
        public RsafDbContext()
            : base("name=RsafDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RSAF_SITE> RSAF_SITE { get; set; }
        public virtual DbSet<RSAF_TYPE> RSAF_TYPE { get; set; }
        public virtual DbSet<RSAF_ARCHIVE> RSAF_ARCHIVE { get; set; }
        public virtual DbSet<RSAF_DETAIL> RSAF_DETAIL { get; set; }
        public virtual DbSet<RSAF_DETAIL_HIST> RSAF_DETAIL_HIST { get; set; }
        public virtual DbSet<RSAF_MASTER> RSAF_MASTER { get; set; }
        public virtual DbSet<RSAF_MASTER_HIST> RSAF_MASTER_HIST { get; set; }
    }
}
