//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSAF_Forms
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSAF_DETAIL_HIST
    {
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public bool STATUS { get; set; }
        public long MASTER_ID { get; set; }
        public long DETAIL_ID { get; set; }
        public string POITEM { get; set; }
        public string MDR { get; set; }
        public string PART_NO { get; set; }
        public string SERIAL { get; set; }
        public Nullable<short> QTYREC { get; set; }
        public bool WARR { get; set; }
        public string OONUM { get; set; }
        public string PSIREF { get; set; }
        public string DESPTOBA { get; set; }
        public Nullable<short> QTYSCRP { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> RECDATE { get; set; }
        public Nullable<System.DateTime> PSIDATE { get; set; }
        public Nullable<System.DateTime> DESPDATE { get; set; }
        public Nullable<short> BAEQTY { get; set; }
        public string BAESER { get; set; }
        public Nullable<System.DateTime> BAESENT { get; set; }
        public string OUTPART { get; set; }
        public Nullable<System.DateTime> PROMISE { get; set; }
        public Nullable<bool> POIC { get; set; }
        public Nullable<decimal> RCP { get; set; }
        public bool ARCHIVE { get; set; }
        public Nullable<System.DateTime> CTRT_DATE { get; set; }
        public string QUOTE_REF { get; set; }
        public Nullable<System.DateTime> QUOTE_REF_DATE { get; set; }
        public bool INVOICE_PAID { get; set; }
        public Nullable<System.DateTime> INVOICE_REQUESTED { get; set; }
        public Nullable<int> ENG_MARK { get; set; }
        public Nullable<int> HOURS_NEW { get; set; }
        public string HOURS_REP { get; set; }
        public string RFR { get; set; }
        public Nullable<int> EX_ENGINE { get; set; }
        public string MODULE_TEXT { get; set; }
        public Nullable<decimal> ACC_STG { get; set; }
        public Nullable<decimal> EURO { get; set; }
        public Nullable<decimal> PAEURO { get; set; }
        public Nullable<System.DateTime> FLEX_DATE { get; set; }
        public string INVOICE_NO { get; set; }
        public Nullable<long> SALES_DOCUMENT { get; set; }
        public string VENDOR { get; set; }
        public string VENDOR_COFC { get; set; }
        public Nullable<decimal> VENDOR_MATERIAL_COST { get; set; }
        public Nullable<decimal> VENDOR_LABOR_COST { get; set; }
        public Nullable<long> PO_REQ { get; set; }
        public Nullable<long> RR_PO { get; set; }
        public string QUALITY_NO { get; set; }
        public Nullable<long> SAP_SES { get; set; }
        public string AWB_DETAILS { get; set; }
        public string FLEX1 { get; set; }
        public string FLEX2 { get; set; }
        public string FLEX3 { get; set; }
        public string FLEX4 { get; set; }
    
        public virtual RSAF_DETAIL RSAF_DETAIL { get; set; }
    }
}
